#!/bin/bash

exec java -XX:PermSize=128m -XX:MaxPermSize=256m -Xms512m -Xmx1g -XX:+UseParallelGC -cp "`dirname $0`/jars/*" org.vertx.java.platform.impl.cli.Starter run vertx.classloader.Verticle -instances 2